name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      
      - name: Build step
        run: deno task build
      
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "tunthuntan-portfolio"
          entrypoint: "main.ts"